services:
  application:
    build: .
    env_file: ./envs/.env.development
    environment:
      DB_URL: postgresql://fake-user:fake-pass@database:5432/fake-db?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - backend

  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: fake-user
      POSTGRES_PASSWORD: fake-pass
      POSTGRES_DB: fake-db
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
